name: tiled
version: 0.8.2
description: A Dart Tiled library. Parse your TMX files into useful representations. Compatible with Flame.
homepage: https://github.com/flame-engine/tiled.dart

environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  archive: ^3.3.0
  meta: ^1.7.0
  xml: ^5.4.1

dev_dependencies:
  test: any
  dartdoc: ^0.42.0
  flame_lint: ^0.0.1
