name: tiled
version: 0.5.1
description: A Dart Tiled library. Parse your TMX files into useful representations. Compatible with Flame.
homepage: https://github.com/flame-engine/tiled.dart

dependencies:
  archive: ^2.0.13
  xml: ^4.2.0

dev_dependencies:
  test: any

environment:
  sdk: ">=2.3.0 <3.0.0"
