name: tiled
version: 0.8.4
description: A Dart Tiled library. Parse your TMX files into useful representations. Compatible with Flame.
homepage: https://github.com/flame-engine/tiled.dart

environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  archive: ^3.3.0
  flutter:
    sdk: flutter
  meta: ^1.7.0
  xml: ^5.4.1

dev_dependencies:
  dartdoc: ^4.1.0
  test: any
  flame_lint: ^0.1.2
