name: tiled
version: 0.11.0
description: A Dart Tiled library. Parse your TMX files into useful representations. Compatible with Flame.
homepage: https://github.com/flame-engine/tiled.dart

environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  archive: ^3.3.0
  collection: ^1.16.0
  meta: ^1.7.0
  xml: ^6.1.0

dev_dependencies:
  dartdoc: ^6.0.1
  test: ^1.24.8
